[project]
name = "banking-workflow-django-mongo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DacioSB", email = "dacio.bezerra@ccc.ufcg.edu.br" }
]
requires-python = ">=3.10"
dependencies = [
    "django-mongodb-backend==5.2.1",
    "openai>=3.13.0",
    "pymongo==4.17.0",
    "python-dotenv==1.2.2",
    "voyageai==0.3.7",
]

[project.scripts]
banking-workflow-django-mongo = "banking_workflow_django_mongo:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
